"""Window / lag constants used by feature families.

During migration these mirror src.utils so old and new implementations stay
numerically identical. After step 15 (cut-over), the canonical definitions
move here and src.utils re-exports for any external readers.
"""

from __future__ import annotations

from src.utils import (
    C,
    EPS,
    ETA,
    HITRATE_WINDOWS_H,
    K_WARMUP,
    LAGS_F,
    M,
    N_WARMUP,
    PHI,
    VOL_PAIRS,
    WINDOWS_B,
    WINDOWS_BARRIER,
    WINDOWS_BASIS,
    WINDOWS_BPLUS,
    WINDOWS_BREAKOUT,
    WINDOWS_CANDLE_ROLL,
    WINDOWS_CORR,
    WINDOWS_EXCURSION,
    WINDOWS_F,
    WINDOWS_FLOW_CSUM,
    WINDOWS_FUNDING,
    WINDOWS_H,
    WINDOWS_LIQ_AMIHUD,
    WINDOWS_LIQ_RPV,
    WINDOWS_LOGP_Z,
    WINDOWS_MAXRET,
    WINDOWS_OFI_IMPULSE,
    WINDOWS_OI_CHG,
    WINDOWS_OPTIONS,
    WINDOWS_PENTROPY,
    WINDOWS_RSI,
    WINDOWS_VOL_DECOMP,
    WINDOWS_VOL_IDX,
    WINDOWS_VOL_OHLC,
)

__all__ = [
    "C",
    "EPS",
    "ETA",
    "HITRATE_WINDOWS_H",
    "K_WARMUP",
    "LAGS_F",
    "M",
    "N_WARMUP",
    "PHI",
    "VOL_PAIRS",
    "WINDOWS_B",
    "WINDOWS_BARRIER",
    "WINDOWS_BASIS",
    "WINDOWS_BPLUS",
    "WINDOWS_BREAKOUT",
    "WINDOWS_CANDLE_ROLL",
    "WINDOWS_CORR",
    "WINDOWS_EXCURSION",
    "WINDOWS_F",
    "WINDOWS_FLOW_CSUM",
    "WINDOWS_FUNDING",
    "WINDOWS_H",
    "WINDOWS_LIQ_AMIHUD",
    "WINDOWS_LIQ_RPV",
    "WINDOWS_LOGP_Z",
    "WINDOWS_MAXRET",
    "WINDOWS_OFI_IMPULSE",
    "WINDOWS_OI_CHG",
    "WINDOWS_OPTIONS",
    "WINDOWS_PENTROPY",
    "WINDOWS_RSI",
    "WINDOWS_VOL_DECOMP",
    "WINDOWS_VOL_IDX",
    "WINDOWS_VOL_OHLC",
]
