"""Window / lag constants used by feature families.

During migration these mirror src.utils so old and new implementations stay
numerically identical. After step 15 (cut-over), the canonical definitions
move here and src.utils re-exports for any external readers.
"""

from __future__ import annotations

from src.utils import (
    C,
    EPS,
    ETA,
    HALFLIVES_EQ,
    HITRATE_WINDOWS_H,
    K_WARMUP,
    LAGS_F,
    M,
    N_WARMUP,
    PHI,
    PIVOT_Q_VALUES,
    VOL_PAIRS,
    WINDOWS_B,
    WINDOWS_BARRIER,
    WINDOWS_BASIS,
    WINDOWS_BPLUS,
    WINDOWS_BREAKOUT,
    WINDOWS_CANDLE_ROLL,
    WINDOWS_CORR,
    WINDOWS_EQ,
    WINDOWS_EQ_PAIRS,
    WINDOWS_EXCURSION,
    WINDOWS_EXTREME,
    WINDOWS_F,
    WINDOWS_FLOW_CSUM,
    WINDOWS_FLOW_PRESSURE,
    WINDOWS_FUNDING,
    WINDOWS_H,
    WINDOWS_LIQ_AMIHUD,
    WINDOWS_LIQ_RPV,
    WINDOWS_LOGP_Z,
    WINDOWS_MAXRET,
    WINDOWS_OFI_IMPULSE,
    WINDOWS_OI_CHG,
    WINDOWS_OI_REGIME,
    WINDOWS_OPTIONS,
    WINDOWS_PENTROPY,
    WINDOWS_PIVOT,
    WINDOWS_QUAD_TREND,
    WINDOWS_RSI,
    WINDOWS_VOL_DECOMP,
    WINDOWS_VOL_IDX,
    WINDOWS_VOL_JUMP,
    WINDOWS_VOL_OHLC,
    WINDOWS_VOL_SIGNED,
)

__all__ = [
    "C",
    "EPS",
    "ETA",
    "HALFLIVES_EQ",
    "HITRATE_WINDOWS_H",
    "K_WARMUP",
    "LAGS_F",
    "M",
    "N_WARMUP",
    "PHI",
    "PIVOT_Q_VALUES",
    "VOL_PAIRS",
    "WINDOWS_B",
    "WINDOWS_BARRIER",
    "WINDOWS_BASIS",
    "WINDOWS_BPLUS",
    "WINDOWS_BREAKOUT",
    "WINDOWS_CANDLE_ROLL",
    "WINDOWS_CORR",
    "WINDOWS_EQ",
    "WINDOWS_EQ_PAIRS",
    "WINDOWS_EXCURSION",
    "WINDOWS_EXTREME",
    "WINDOWS_F",
    "WINDOWS_FLOW_CSUM",
    "WINDOWS_FLOW_PRESSURE",
    "WINDOWS_FUNDING",
    "WINDOWS_H",
    "WINDOWS_LIQ_AMIHUD",
    "WINDOWS_LIQ_RPV",
    "WINDOWS_LOGP_Z",
    "WINDOWS_MAXRET",
    "WINDOWS_OFI_IMPULSE",
    "WINDOWS_OI_CHG",
    "WINDOWS_OI_REGIME",
    "WINDOWS_OPTIONS",
    "WINDOWS_PENTROPY",
    "WINDOWS_PIVOT",
    "WINDOWS_QUAD_TREND",
    "WINDOWS_RSI",
    "WINDOWS_VOL_DECOMP",
    "WINDOWS_VOL_IDX",
    "WINDOWS_VOL_JUMP",
    "WINDOWS_VOL_OHLC",
    "WINDOWS_VOL_SIGNED",
]
